### ISSUE TITLE
not able to send html email !!

### ISSUE THREAD

**Issue by hboumedane** [wisdom-framework/wisdom-mailer#7]
I'm using wisdom-mailer to send html mail like this :+1: 

```java
                mailer.send(new Mail()
                        .to("test@test.com")
                        .subject("test mail")
                        .body("<html><body><h1>Hello</h1><p>Here is data using accent and symbols - å é è ß ∑ Ω " +
                                "</p></body></html>")
                        .charset(Charsets.UTF_8.toString())
                        .subType("html"));

```
but the received mail is not formatted as HTML.

**Comment by cescoffier** [comment]
What do you mean by not formatted as HTML ? 
My mail client read it as HTML.

**Comment by cescoffier** [comment]
Here is the mail content, looks good to me:


````
MIME-Version: 1.0
Content-Type: multipart/mixed; 
	boundary="----=_Part_0_1591063329.1420194920370"

------=_Part_0_1591063329.1420194920370
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<html><body><h1>Hello</h1><p>Here is data using accent and symbols - =C3=A5=
 =C3=A9 =C3=A8 =C3=9F =E2=88=91 =CE=A9 </p></body></html>
------=_Part_0_1591063329.1420194920370--
````

**Comment by hboumedane** [comment]
her what I received with my mail client : 
```
------=_Part_2_1350821031.1420196460502
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit

<html><body><h1>Hello</h1><p>Here is data using accent and symbols ? ? ? ? ? </p></body></html>
------=_Part_2_1350821031.1420196460502--
```

**Comment by cescoffier** [comment]
I'm surprised by the `_Part_2`. 
Did you try from the 'master' version ?

**Comment by hboumedane** [comment]
yes , i'm using wisdom-mailer 0.4 version with wisdom 0.6.5 ??

**Comment by cescoffier** [comment]
That's might be the issue. We had this bug where the subType was ignored.

**Comment by cescoffier** [comment]
Anyway to update to latest ?

**Comment by hboumedane** [comment]
sorry to bother you, i'm having an error with my project when i updated wisdom to 0.7 : 
```
document.write('<script  id=\"template-upload\" type="text/x-tmpl">
JSC_PARSE_ERROR. Parse error. String continuations are not supported in this language mode.

```
after that i can test the email sending with the latest version..

**Comment by cescoffier** [comment]
Where do you see this message ? In a template ? If so can you sent it to me.

Sent from my iPhone

On 2 janv. 2015, at 12:49, hboumedane <notifications@github.com> wrote:

sorry to bother you, i'm having an error with my project when i updated
wisdom to 0.7 :

document.write('<script  id=\"template-upload\" type="text/x-tmpl">
JSC_PARSE_ERROR. Parse error. String continuations are not supported
in this language mode.


after that i can test the email sending with the latest version..

—
Reply to this email directly or view it on GitHub
<https://github.com/wisdom-framework/wisdom-mailer/issues/7#issuecomment-68521719>
.

**Comment by hboumedane** [comment]
no it's inside a javascript file , here the file : 
```javascript
document.write('<script  id=\"template-upload\" type="text/x-tmpl">\
\{\% for (var i=0, file; file=o.files[i]; i++) { %}\
<tr class="template-upload fade">\
    <td>\
        <span class="preview"></span>\
    </td>\
    <td>\
        <p class="name">{%=file.name%}</p>\
        <strong class="error text-danger"></strong>\
    </td>\
    <td>\
        <p class="size">En cours...</p>\
        <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">\
             <div class="progress-bar progress-bar-success" style="width:0%;">\
             </div>\
        </div>\
    </td>\
    <td>\
         {% if (!i) { %}\
             <button class="btn btn-warning cancel">\
               <i class="glyphicon glyphicon-ban-circle"></i>\
                <span>Annuler</span>\
                </button>\
            {% } %}\
    </td>\
   \
</tr>\
{% } %}\
</script>\
\
\
<script id="template-download" type="text/x-tmpl">\
{% for (var i=0, file; file=o.files[i]; i++) { %}\
    <tr class="template-download fade">\
    <td>\
    <span class="preview">\
        {% if (file.thumbnailUrl) { %}\
            <img src="{%=file.thumbnailUrl%}" style="height: 180px; width: 171px; display: block;">\
        {% } %}\
    </span>\
    </td>\
    <td>\
    <p class="name">\
            <span>{%=file.name%}</span>\
    </p>\
    \
    {% if (file.error) { %}\
        <div><span class="label label-danger">Error</span> {%=file.error%}</div>\
        {% } %}\
    </td>\
    <td>\
    <span class="size">{%=o.formatFileSize(file.size)%}</span>\
    </td>\
    </tr>\
    {% } %}\
    </script>');
```

**Comment by cescoffier** [comment]
Does it happen during the build ? In that case send me the complete error. It may be related to Google Closure


On 2 janvier 2015 at 13:07:20, hboumedane (notifications@github.com) wrote:

no it's inside a javascript file , here the file :

document.write('<script  id=\"template-upload\" type="text/x-tmpl">\
\{\% for (var i=0, file; file=o.files[i]; i++) { %}\
<tr class="template-upload fade">\
    <td>\
        <span class="preview"></span>\
    </td>\
    <td>\
        <p class="name">{%=file.name%}</p>\
        <strong class="error text-danger"></strong>\
    </td>\
    <td>\
        <p class="size">En cours...</p>\
        <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">\
             <div class="progress-bar progress-bar-success" style="width:0%;">\
             </div>\
        </div>\
    </td>\
    <td>\
         {% if (!i) { %}\
             <button class="btn btn-warning cancel">\
               <i class="glyphicon glyphicon-ban-circle"></i>\
                <span>Annuler</span>\
                </button>\
            {% } %}\
    </td>\
   \
</tr>\
{% } %}\
</script>\
\
\
<script id="template-download" type="text/x-tmpl">\
{% for (var i=0, file; file=o.files[i]; i++) { %}\
    <tr class="template-download fade">\
    <td>\
    <span class="preview">\
        {% if (file.thumbnailUrl) { %}\
            <img src="{%=file.thumbnailUrl%}" style="height: 180px; width: 171px; display: block;">\
        {% } %}\
    </span>\
    </td>\
    <td>\
    <p class="name">\
            <span>{%=file.name%}</span>\
    </p>\
    \
    {% if (file.error) { %}\
        <div><span class="label label-danger">Error</span> {%=file.error%}</div>\
        {% } %}\
    </td>\
    <td>\
    <span class="size">{%=o.formatFileSize(file.size)%}</span>\
    </td>\
    </tr>\
    {% } %}\
    </script>');

**Comment by hboumedane** [comment]
yes it happed when i try to build , here the complete error : 
```
[ERROR] JSC_PARSE_ERROR. Parse error. String continuations are not supported in this language mode. at /home/homada/workspace/UserMgtServer/target/classes/assets/js/template.js line 1 : 15
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.578 s
[INFO] Finished at: 2015-01-02T13:39:02+01:00
[INFO] Final Memory: 27M/391M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.wisdom-framework:wisdom-maven-plugin:0.7.0:compile-javascript (default-compile-javascript) on project user.mgt.server: Error while compile JavaScript files, check log for more details -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.wisdom-framework:wisdom-maven-plugin:0.7.0:compile-javascript (default-compile-javascript) on project user.mgt.server: Error while compile JavaScript files, check log for more details
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error while compile JavaScript files, check log for more details
        at org.wisdom.maven.mojos.JavaScriptCompilerMojo.execute(JavaScriptCompilerMojo.java:112)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: org.wisdom.maven.WatchingException: Error while compile JavaScript files, check log for more details
        at org.wisdom.maven.mojos.JavaScriptCompilerMojo.compile(JavaScriptCompilerMojo.java:325)
        at org.wisdom.maven.mojos.JavaScriptCompilerMojo.execute(JavaScriptCompilerMojo.java:104)
        ... 21 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

the template.js is the one I sent to you ...

**Comment by cescoffier** [comment]
Ok,

So, in your pom file, under the wisdom-maven-plugin configuration add:

````
<skipGoogleClosure>true</skipGoogleClosure>
````

It should be something like this:

````
        <plugin>
                <groupId>org.wisdom-framework</groupId>
                <artifactId>wisdom-maven-plugin</artifactId>
                <version>0.7.0</version>
                <extensions>true</extensions>
                <configuration>
                    <skipGoogleClosure>true</skipGoogleClosure>
                </configuration>
            </plugin>
````

Google Closure seems unable to 'check' your JavaScript code. It may be interesting to know why as it gives you good hints about how to write JavaScript code that will have the same semantic everywhere.

**Comment by hboumedane** [comment]
Thanks !! it works , no more javascript error...
did you deployed the 0.5-snapshot version for the mailer and the jdbc project ??
i can't found them ?

**Comment by cescoffier** [comment]
Normally yes, they should be on OSS Snapshot:

You should have it using:

```
 <repositories>
        <repository>
            <id>oss-snapshot</id>
            <name>oss-snapshot</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>oss-snapshot</id>
            <name>oss-snapshot</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        </pluginRepository>
    </pluginRepositories>
```

Anyway, gonna cut a release of jdbc and mail projects soonish (this weekend or next week).

**Comment by hboumedane** [comment]
Tanks for your help,
the mail is working correctly now.. 
here the proof : 

```
------=_Part_0_1464160316.1420206089861
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 7bit

<html><head></head><body><h1>Bonjour </h1><p>voici votre nouveau mot de passe :******</p></body></html>
------=_Part_0_1464160316.1420206089861--
```

**Comment by cescoffier** [comment]
Closing after confirmation given by @hboumedane
